"""create users table

Revision ID: 12aec2be73d8
Revises: 3b9807b9d52e
Create Date: 2023-01-06 01:56:50.731646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12aec2be73d8'
down_revision = '3b9807b9d52e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
